package swimmingcompetition;

import Model.Swimmer;
import Model.SwimmingEvent;
import Model.ScoreBoard;
import Model.SwimLane;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.Map;
import java.util.Queue;
import java.util.concurrent.locks.Condition;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Lahiru
 */
public class SwimmingPoolGUI extends javax.swing.JDialog {

    private final Map<Swimmer, JLabel> mapSwimmers;
    private final Map<SwimLane, JLabel> mapSwimLanes;
    private final Map<Swimmer, JLabel> mapLaneTime;
    private final Map<Swimmer , JLabel> mapTouchPads;
    private final Lock lock;
    private final Condition condition;
    private final SwimmingEvent swimmingEvent;
    private final ScoreBoard scoreBoard;

    /**
     * Creates new form SwimmingPoolGUI
     *
     * @param parent
     * @param modal
     * @param swimmingEvent
     */
    public SwimmingPoolGUI(java.awt.Frame parent, boolean modal, SwimmingEvent swimmingEvent) {
        super(parent, modal);
        initComponents();
        mapSwimmers = new HashMap<>();
        mapSwimLanes = new HashMap<>();
        mapLaneTime = new HashMap<>();
        mapTouchPads = new HashMap<>();
        
        lock = new ReentrantLock();                                             // creating new lock
        condition = lock.newCondition();                                        // creating new condtion
        this.swimmingEvent = swimmingEvent;
        this.scoreBoard = swimmingEvent.getSwimmingPool().getScoreBoard();

        mapSwimmers(swimmingEvent);

        // set visible false some lables and a panel
        pnlFinalResults.setVisible(false);
        lbl4.setVisible(false);
        lblFourthPlace.setVisible(false);
        lblFourthTime.setVisible(false);
        lbl5.setVisible(false);
        lblFifthPlace.setVisible(false);
        lblFifthTime.setVisible(false);
        // end of invisibling labels

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPool = new javax.swing.JPanel();
        Swimmer1 = new javax.swing.JLabel();
        Swimmer2 = new javax.swing.JLabel();
        Swimmer3 = new javax.swing.JLabel();
        Swimmer4 = new javax.swing.JLabel();
        Swimmer5 = new javax.swing.JLabel();
        TouchPad1 = new javax.swing.JLabel();
        TouchPad2 = new javax.swing.JLabel();
        TouchPad3 = new javax.swing.JLabel();
        TouchPad4 = new javax.swing.JLabel();
        TouchPad5 = new javax.swing.JLabel();
        swimLane1 = new javax.swing.JLabel();
        swimLane2 = new javax.swing.JLabel();
        swimLane3 = new javax.swing.JLabel();
        swimLane5 = new javax.swing.JLabel();
        swimLane4 = new javax.swing.JLabel();
        pnlPavilion = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pnlScoreBoardLayer = new javax.swing.JPanel();
        pnlScoreBoard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNameSwimmer1 = new javax.swing.JLabel();
        lblNameSwimmer2 = new javax.swing.JLabel();
        lblNameSwimmer3 = new javax.swing.JLabel();
        lblNameSwimmer4 = new javax.swing.JLabel();
        lblNameSwimmer5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTimeLane1 = new javax.swing.JLabel();
        lblTimeLane2 = new javax.swing.JLabel();
        lblTimeLane3 = new javax.swing.JLabel();
        lblTimeLane4 = new javax.swing.JLabel();
        lblTimeLane5 = new javax.swing.JLabel();
        pnlFinalResults = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lblFourthPlace = new javax.swing.JLabel();
        lblFourthTime = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lblFifthPlace = new javax.swing.JLabel();
        lblFifthTime = new javax.swing.JLabel();
        pnlFirst = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lblFirstPlace = new javax.swing.JLabel();
        lblFirstTime = new javax.swing.JLabel();
        pnlSecond = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        lblSecondPlace = new javax.swing.JLabel();
        lblSecondTime = new javax.swing.JLabel();
        pnlThird = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        lblThirdPlace = new javax.swing.JLabel();
        lblThirdTime = new javax.swing.JLabel();
        btnWhistle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnlPool.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Swimmer1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        pnlPool.add(Swimmer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 41, -1, -1));

        Swimmer2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        pnlPool.add(Swimmer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 93, -1, -1));

        Swimmer3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        pnlPool.add(Swimmer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 142, -1, -1));

        Swimmer4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        pnlPool.add(Swimmer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 201, -1, -1));

        Swimmer5.setBackground(new java.awt.Color(255, 255, 255));
        Swimmer5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        pnlPool.add(Swimmer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        TouchPad1.setBackground(new java.awt.Color(255, 0, 51));
        TouchPad1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TouchPad1.setForeground(new java.awt.Color(255, 0, 51));
        TouchPad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extra/TouchPadInactive.png"))); // NOI18N
        TouchPad1.setToolTipText("");
        TouchPad1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlPool.add(TouchPad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 39, 20, 30));

        TouchPad2.setBackground(new java.awt.Color(255, 0, 51));
        TouchPad2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TouchPad2.setForeground(new java.awt.Color(255, 0, 51));
        TouchPad2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extra/TouchPadInactive.png"))); // NOI18N
        TouchPad2.setToolTipText("");
        TouchPad2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlPool.add(TouchPad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 88, 20, 33));

        TouchPad3.setBackground(new java.awt.Color(255, 0, 51));
        TouchPad3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TouchPad3.setForeground(new java.awt.Color(255, 0, 51));
        TouchPad3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extra/TouchPadInactive.png"))); // NOI18N
        TouchPad3.setToolTipText("");
        TouchPad3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlPool.add(TouchPad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 141, 20, 31));

        TouchPad4.setBackground(new java.awt.Color(255, 0, 51));
        TouchPad4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TouchPad4.setForeground(new java.awt.Color(255, 0, 51));
        TouchPad4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extra/TouchPadInactive.png"))); // NOI18N
        TouchPad4.setToolTipText("");
        TouchPad4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlPool.add(TouchPad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 190, 20, 32));

        TouchPad5.setBackground(new java.awt.Color(255, 0, 51));
        TouchPad5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TouchPad5.setForeground(new java.awt.Color(255, 0, 51));
        TouchPad5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extra/TouchPadInactive.png"))); // NOI18N
        TouchPad5.setToolTipText("");
        TouchPad5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlPool.add(TouchPad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 239, 20, 34));

        swimLane1.setBackground(new java.awt.Color(51, 204, 255));
        swimLane1.setForeground(new java.awt.Color(51, 204, 255));
        swimLane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        swimLane1.setOpaque(true);
        pnlPool.add(swimLane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 30, 653, 50));

        swimLane2.setBackground(new java.awt.Color(51, 204, 255));
        swimLane2.setForeground(new java.awt.Color(51, 204, 255));
        swimLane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        swimLane2.setOpaque(true);
        pnlPool.add(swimLane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 80, 653, 50));

        swimLane3.setBackground(new java.awt.Color(51, 204, 255));
        swimLane3.setForeground(new java.awt.Color(51, 204, 255));
        swimLane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        swimLane3.setOpaque(true);
        pnlPool.add(swimLane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 130, 653, 51));

        swimLane5.setBackground(new java.awt.Color(51, 204, 255));
        swimLane5.setForeground(new java.awt.Color(51, 204, 255));
        swimLane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        swimLane5.setOpaque(true);
        pnlPool.add(swimLane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 231, 653, 50));

        swimLane4.setBackground(new java.awt.Color(51, 204, 255));
        swimLane4.setForeground(new java.awt.Color(51, 204, 255));
        swimLane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        swimLane4.setOpaque(true);
        pnlPool.add(swimLane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 181, 653, 50));

        pnlPavilion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pavilion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 16))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extra/Spectator.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extra/Spectator.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extra/Spectator.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extra/Spectator.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extra/Spectator.png"))); // NOI18N

        javax.swing.GroupLayout pnlPavilionLayout = new javax.swing.GroupLayout(pnlPavilion);
        pnlPavilion.setLayout(pnlPavilionLayout);
        pnlPavilionLayout.setHorizontalGroup(
            pnlPavilionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPavilionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 422, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(23, 23, 23))
        );
        pnlPavilionLayout.setVerticalGroup(
            pnlPavilionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPavilionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlPavilionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pnlScoreBoardLayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlScoreBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Score Board", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel1.setText("Lane 1");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel2.setText("Lane 2");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel3.setText("Lane 3");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel4.setText("Lane 4");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel5.setText("Lane 5");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Lane #");

        lblNameSwimmer1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblNameSwimmer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameSwimmer1.setText("---");

        lblNameSwimmer2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblNameSwimmer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameSwimmer2.setText("---");

        lblNameSwimmer3.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblNameSwimmer3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameSwimmer3.setText("---");

        lblNameSwimmer4.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblNameSwimmer4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameSwimmer4.setText("---");

        lblNameSwimmer5.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblNameSwimmer5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameSwimmer5.setText("---");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Swimmer Name");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Finishing Time (s)");

        lblTimeLane1.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lblTimeLane1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTimeLane1.setText("---");

        lblTimeLane2.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lblTimeLane2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTimeLane2.setText("---");

        lblTimeLane3.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lblTimeLane3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTimeLane3.setText("---");

        lblTimeLane4.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lblTimeLane4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTimeLane4.setText("---");

        lblTimeLane5.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lblTimeLane5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTimeLane5.setText("---");

        javax.swing.GroupLayout pnlScoreBoardLayout = new javax.swing.GroupLayout(pnlScoreBoard);
        pnlScoreBoard.setLayout(pnlScoreBoardLayout);
        pnlScoreBoardLayout.setHorizontalGroup(
            pnlScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScoreBoardLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlScoreBoardLayout.createSequentialGroup()
                        .addGroup(pnlScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlScoreBoardLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(55, 55, 55)
                                .addComponent(lblNameSwimmer3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(lblTimeLane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlScoreBoardLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(55, 55, 55)
                                .addComponent(lblNameSwimmer4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(lblTimeLane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlScoreBoardLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(55, 55, 55)
                                .addComponent(lblNameSwimmer1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(lblTimeLane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlScoreBoardLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(55, 55, 55)
                                .addComponent(lblNameSwimmer2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(lblTimeLane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlScoreBoardLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblTimeLane5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(pnlScoreBoardLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel7)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel8))
                    .addGroup(pnlScoreBoardLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(55, 55, 55)
                        .addComponent(lblNameSwimmer5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlScoreBoardLayout.setVerticalGroup(
            pnlScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScoreBoardLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(pnlScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNameSwimmer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTimeLane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(pnlScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNameSwimmer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTimeLane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(pnlScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNameSwimmer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTimeLane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(pnlScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNameSwimmer4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTimeLane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(pnlScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNameSwimmer5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTimeLane5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlScoreBoardLayer.add(pnlScoreBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        pnlScoreBoard.getAccessibleContext().setAccessibleDescription("");

        pnlFinalResults.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 51, 0));
        jLabel12.setText("FINAL RESULTS");

        lbl4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lbl4.setText("4");

        lblFourthPlace.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblFourthPlace.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFourthPlace.setText("Swimmer4");

        lblFourthTime.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblFourthTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFourthTime.setText("Time4");

        lbl5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lbl5.setText("5");

        lblFifthPlace.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblFifthPlace.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFifthPlace.setText("Swimmer5");

        lblFifthTime.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblFifthTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFifthTime.setText("Time5");

        pnlFirst.setBackground(new java.awt.Color(0, 153, 0));
        pnlFirst.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lbl1.setText("1");

        lblFirstPlace.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblFirstPlace.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFirstPlace.setText("Swimmer1");

        lblFirstTime.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblFirstTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFirstTime.setText("Time1");

        javax.swing.GroupLayout pnlFirstLayout = new javax.swing.GroupLayout(pnlFirst);
        pnlFirst.setLayout(pnlFirstLayout);
        pnlFirstLayout.setHorizontalGroup(
            pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFirstLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl1)
                .addGap(18, 18, 18)
                .addComponent(lblFirstPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(lblFirstTime, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        pnlFirstLayout.setVerticalGroup(
            pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFirstLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstPlace)
                    .addComponent(lbl1)
                    .addComponent(lblFirstTime))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnlSecond.setBackground(new java.awt.Color(0, 204, 51));
        pnlSecond.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl2.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        lbl2.setText("2");

        lblSecondPlace.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        lblSecondPlace.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSecondPlace.setText("Swimmer2");

        lblSecondTime.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        lblSecondTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSecondTime.setText("Time2");

        javax.swing.GroupLayout pnlSecondLayout = new javax.swing.GroupLayout(pnlSecond);
        pnlSecond.setLayout(pnlSecondLayout);
        pnlSecondLayout.setHorizontalGroup(
            pnlSecondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecondLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl2)
                .addGap(18, 18, 18)
                .addComponent(lblSecondPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSecondTime, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnlSecondLayout.setVerticalGroup(
            pnlSecondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecondLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSecondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(lblSecondPlace)
                    .addComponent(lblSecondTime))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlThird.setBackground(new java.awt.Color(51, 255, 51));
        pnlThird.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lbl3.setText("3 ");

        lblThirdPlace.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblThirdPlace.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblThirdPlace.setText("Swimmer3");

        lblThirdTime.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblThirdTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblThirdTime.setText("Time3");

        javax.swing.GroupLayout pnlThirdLayout = new javax.swing.GroupLayout(pnlThird);
        pnlThird.setLayout(pnlThirdLayout);
        pnlThirdLayout.setHorizontalGroup(
            pnlThirdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThirdLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblThirdPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblThirdTime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnlThirdLayout.setVerticalGroup(
            pnlThirdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThirdLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlThirdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3)
                    .addComponent(lblThirdPlace)
                    .addComponent(lblThirdTime))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFinalResultsLayout = new javax.swing.GroupLayout(pnlFinalResults);
        pnlFinalResults.setLayout(pnlFinalResultsLayout);
        pnlFinalResultsLayout.setHorizontalGroup(
            pnlFinalResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFinalResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFinalResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFinalResultsLayout.createSequentialGroup()
                        .addComponent(lbl5)
                        .addGap(18, 18, 18)
                        .addComponent(lblFifthPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFinalResultsLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFourthPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFinalResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFourthTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFifthTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addComponent(pnlSecond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlThird, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFinalResultsLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFinalResultsLayout.setVerticalGroup(
            pnlFinalResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinalResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(39, 39, 39)
                .addComponent(pnlFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlThird, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(pnlFinalResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl4)
                    .addComponent(lblFourthPlace)
                    .addComponent(lblFourthTime))
                .addGap(33, 33, 33)
                .addGroup(pnlFinalResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl5)
                    .addComponent(lblFifthPlace)
                    .addComponent(lblFifthTime))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnlScoreBoardLayer.add(pnlFinalResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 440, 330));

        btnWhistle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extra/whistle8.png"))); // NOI18N
        btnWhistle.setText("Whistle");
        btnWhistle.setBorderPainted(false);
        btnWhistle.setContentAreaFilled(false);
        btnWhistle.setFocusPainted(false);
        btnWhistle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWhistleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPavilion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlPool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWhistle))
                .addGap(18, 18, 18)
                .addComponent(pnlScoreBoardLayer, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(pnlPavilion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(pnlPool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnWhistle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(pnlScoreBoardLayer, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnWhistleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWhistleActionPerformed
        boolean isWhistled = false;
        isWhistled = swimmingEvent.getHeadOfTheJudges().doWhistle();
        if (isWhistled) {
            mapSwimLanes(swimmingEvent);
            final String swimmingStyle = this.swimmingEvent.getSwimmingStyle();
            SwingUtilities.invokeLater(new Runnable() {                         // EDT

                @Override
                public void run() {
                    startTheGame(swimmingStyle);
                    displayFinalResults();
                }

            });
            this.scoreBoard.powerUp();                                              // start the ScoreBoard
            this.swimmingEvent.setCompleted();                                      // event has started 
            btnWhistle.setVisible(false);
        }
    }//GEN-LAST:event_btnWhistleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwimmingPoolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwimmingPoolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwimmingPoolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwimmingPoolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                SwimmingPoolGUI dialog = new SwimmingPoolGUI(new javax.swing.JFrame(), true, new SwimmingEvent("s", "s", "s"));
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Swimmer1;
    private javax.swing.JLabel Swimmer2;
    private javax.swing.JLabel Swimmer3;
    private javax.swing.JLabel Swimmer4;
    private javax.swing.JLabel Swimmer5;
    private javax.swing.JLabel TouchPad1;
    private javax.swing.JLabel TouchPad2;
    private javax.swing.JLabel TouchPad3;
    private javax.swing.JLabel TouchPad4;
    private javax.swing.JLabel TouchPad5;
    private javax.swing.JButton btnWhistle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lblFifthPlace;
    private javax.swing.JLabel lblFifthTime;
    private javax.swing.JLabel lblFirstPlace;
    private javax.swing.JLabel lblFirstTime;
    private javax.swing.JLabel lblFourthPlace;
    private javax.swing.JLabel lblFourthTime;
    private javax.swing.JLabel lblNameSwimmer1;
    private javax.swing.JLabel lblNameSwimmer2;
    private javax.swing.JLabel lblNameSwimmer3;
    private javax.swing.JLabel lblNameSwimmer4;
    private javax.swing.JLabel lblNameSwimmer5;
    private javax.swing.JLabel lblSecondPlace;
    private javax.swing.JLabel lblSecondTime;
    private javax.swing.JLabel lblThirdPlace;
    private javax.swing.JLabel lblThirdTime;
    private javax.swing.JLabel lblTimeLane1;
    private javax.swing.JLabel lblTimeLane2;
    private javax.swing.JLabel lblTimeLane3;
    private javax.swing.JLabel lblTimeLane4;
    private javax.swing.JLabel lblTimeLane5;
    private javax.swing.JPanel pnlFinalResults;
    private javax.swing.JPanel pnlFirst;
    private javax.swing.JPanel pnlPavilion;
    private static javax.swing.JPanel pnlPool;
    private javax.swing.JPanel pnlScoreBoard;
    private javax.swing.JPanel pnlScoreBoardLayer;
    private javax.swing.JPanel pnlSecond;
    private javax.swing.JPanel pnlThird;
    private javax.swing.JLabel swimLane1;
    private javax.swing.JLabel swimLane2;
    private javax.swing.JLabel swimLane3;
    private javax.swing.JLabel swimLane4;
    private javax.swing.JLabel swimLane5;
    // End of variables declaration//GEN-END:variables

    private void mapSwimmers(SwimmingEvent event) {

        try {
            Queue<JLabel> lblSwimmers = new LinkedList<>(Arrays.asList(
                    new JLabel[]{this.Swimmer1, this.Swimmer2, this.Swimmer3,
                        this.Swimmer4, this.Swimmer5}));

            Queue<JLabel> lblNameSwimmers = new LinkedList<>(Arrays.asList(
                    new JLabel[]{this.lblNameSwimmer1, this.lblNameSwimmer2,
                        this.lblNameSwimmer3, this.lblNameSwimmer4,
                        this.lblNameSwimmer5}));

            Queue<JLabel> lblTimeLanes = new LinkedList<>(Arrays.asList(
                    new JLabel[]{this.lblTimeLane1, this.lblTimeLane2, this.lblTimeLane3,
                        this.lblTimeLane4, this.lblTimeLane5}));

            Queue<JLabel> lblTouchPads = new LinkedList<>(Arrays.asList(
                    new JLabel[]{this.TouchPad1, this.TouchPad2, this.TouchPad3,
                        this.TouchPad4, this.TouchPad5}));
            
            int laneNumber = 1;
            for (Swimmer s : event.getSwimmersInEvent()) {

                s.getSwimLane().setLaneNumber(laneNumber++);                    // set the lane number            
                JLabel lblSwimmer = lblSwimmers.poll();
                lblSwimmer.setText("*");
                lblSwimmer.setForeground(s.getDressColor());
                this.mapSwimmers.put(s, lblSwimmer);                            // map swimmer and the relevant label
                lblNameSwimmers.poll().setText(s.getName());                    // set the name of the swimmer to the label in score board gui

                this.mapLaneTime.put(s, lblTimeLanes.poll());
                this.mapTouchPads.put(s, lblTouchPads.poll());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void mapSwimLanes(SwimmingEvent event) {
        Queue<JLabel> lblSwimLanes = new LinkedList<>(Arrays.asList(
                new JLabel[]{this.swimLane1, this.swimLane2, this.swimLane5,
                    this.swimLane3, this.swimLane4}));

        for (Swimmer s : event.getSwimmersInEvent()) {

            JLabel lblSwimLane = lblSwimLanes.poll();
            this.mapSwimLanes.put(s.getSwimLane(), lblSwimLane);
            s.getSwimLane().setLength(lblSwimLane.getSize().width);

        }
    }

    private void mapFinishedEntries() {
        Queue<JLabel> lblFinishedTimes = new LinkedList<>(Arrays.asList(
                new JLabel[]{this.lblFirstTime, this.lblSecondTime,
                    this.lblThirdTime, this.lblFourthTime, this.lblFifthTime}));// queue to store labels

        Queue<JLabel> lblFinishedSwimmers = new LinkedList<>(Arrays.asList(
                new JLabel[]{this.lblFirstPlace, this.lblSecondPlace,
                    this.lblThirdPlace, this.lblFourthPlace,
                    this.lblFifthPlace}));                                      // queue to store labels

        Map<Swimmer, Double> finalResults = scoreBoard.getFinalResults();

        int numberOfSwimmers = finalResults.keySet().size();

        // visible the hidden two labels 
        if (numberOfSwimmers == 4) {
            lbl4.setVisible(true);
        } else if (numberOfSwimmers == 5) {
            lbl4.setVisible(true);
            lbl5.setVisible(true);
        }
        // end of visibling
        boolean Notassigned = true;
        for (Swimmer s : finalResults.keySet()) {
            // assigning text values and visible the labels 
            if (Notassigned) {
                swimmingEvent.setWinner(s);
                MainWindowGUI.setWinner(s.getName(), swimmingEvent);
                Notassigned = false;
            }
            JLabel lblS = lblFinishedSwimmers.poll();
            lblS.setText(s.getName());
            lblS.setVisible(true);

            JLabel lblT = lblFinishedTimes.poll();
            lblT.setText(finalResults.get(s) + "");
            lblT.setVisible(true);
            // end of assining the text values
        }

        pnlScoreBoard.setVisible(false);
        pnlFinalResults.setVisible(true);
    }

    private void startTheGame(final String swimmingStyle) {

        final ArrayList<Swimmer> listSwimmer = new ArrayList<>(mapSwimmers.keySet());
        ArrayList<Thread> threads = new ArrayList<>();
        final ImageIcon imageIcon = new ImageIcon(getClass().getResource("/Extra/TouchPadActive.png"));
        
        for (int i = 0; i < mapSwimmers.size(); i++) {
            final Swimmer swmr = listSwimmer.get(i);
            swmr.setCurrentPosition(mapSwimmers.get(swmr).getX());              // set up the intial position of the JLabel to the swimmer

            threads.add(new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        swmr.slowDown();                                        // lock the thread
                        JLabel lblSwmr = mapSwimmers.get(swmr);
                        swmr.doSwimmingStyle(swimmingStyle);                    // start the game

                        int startPosition = swmr.getCurrentPosition();          // get the currenPosition

                        while ((lblSwmr.getX()
                                <= swmr.getSwimLane().getLength()
                                + startPosition)) {

                            lblSwmr.setLocation(swmr.doLegMovements(),
                                    lblSwmr.getY());
                            swmr.doHandMovements();                             // signall all other threads
                            swmr.speedUp();                                     // wait this thread to gain some higher currentPositions
                        }
                        final double time = swmr.touchTheTouchPad(
                                swimmingEvent.getSwimmingPool());

                        mapLaneTime.get(swmr).setText(time + "");
                        mapTouchPads.get(swmr).setIcon(imageIcon);
                        
                        
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    } finally {
                        swmr.giveUp();
                    }
                }
            }));
        }
        for (Thread run : threads) {
            run.start();
        }

    }

    private void displayFinalResults() {
        new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    scoreBoard.lockTheScoreBoard();                             // Lock this threa with the lock
                    scoreBoard.awaitScoreBoard();                               // wait until swimmers complete the game
                    Thread.sleep(1000);
                    mapFinishedEntries();                                       // setting parameters to the labels
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                } finally {
                    scoreBoard.unlockTheScoreBoard();
                }
            }
        }).start();
    }

}
